1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,4,6],
        [1,3,5],
        [8,4,1]])

sumMat = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[2 4 6]
 [1 3 5]
 [8 4 1]]  is 

[[ 3  6  9]
 [ 5  8 11]
 [15 12 10]] 


2. Write a Python Program to Multiply Two Matrices?

In [2]:
mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 44  51  22]
 [ 81  96  57]
 [126 150  93]] 


3. Write a Python Program to Transpose a Matrix?

In [6]:
def initializeMatrix(n,v=0):
    M=[]             
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def createMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def printMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 
        
def transposeMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result
n=int(input("Enter N for N x N matrix: "))       
M1 = createMatrix(n)
print("Display Array M1 In Matrix Form")
printMatrix(M1,n)
result = initializeMatrix(n)
result = transposeMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)

Enter N for N x N matrix: 2
Enter the element :
1
2
3
4
Display Array M1 In Matrix Form
1 2 
3 4 
Transposed Matrix
[1, 3]
[2, 4]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [9]:
str = input("Enter string: ")
words = str.split()
words.sort()
for word in words:
    print(word)

Enter string: Python is a programming language
Python
a
is
language
programming


5. Write a Python Program to Remove Punctuation From a String?

In [10]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = input("Enter string")
no_punct = ""
for char in str:
    if char not in punctuations:
        no_punct = no_punct + char
print(no_punct)

Enter string'my' name,
my name
